### ISSUE TITLE
安装出现问题

### ISSUE THREAD

**Issue by A1oneR** [BigOrangeQWQ/nonebot_plugin_orangedice#1]
![image](https://user-images.githubusercontent.com/70164765/212853159-d3a53465-827c-484a-82a7-16149cda1e6a.png)
直接安装插件会出现如下问题:
```
01-17 16:51:51 [ERROR] nonebot | Failed to import "nonebot_plugin_orangedice"
Traceback (most recent call last):

  File "bot.py", line 18, in <module>
    nonebot.load_plugin("nonebot_plugin_orangedice")
    │       └ <function load_plugin at 0x7f8096a17670>
    └ <module 'nonebot' from '/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/n...

  File "/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
           │       │           └ 'nonebot_plugin_orangedice'
           │       └ <function PluginManager.load_plugin at 0x7f8096a12a60>
           └ PluginManager(plugins={'nonebot_plugin_orangedice'}, search_path=set())
> File "/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
             │         │             └ 'nonebot_plugin_orangedice'
             │         └ <function import_module at 0x7f8097f41700>
             └ <module 'importlib' from '/usr/lib/python3.8/importlib/__init__.py'>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'nonebot_plugin_orangedice'
           │          └ <function _gcd_import at 0x7f809805e430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
                        └ <module 'nonebot_plugin_orangedice' from '/home/lighthouse/zhenxunbot/nonebot_plugin_orangedice/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/home/lighthouse/zhenxunbot/nonebot_plugin_orangedice/__init__.py", line 9, in <module>
    from nonebot_plugin_orangedice.model import DataContainer

  File "/home/lighthouse/zhenxunbot/nonebot_plugin_orangedice/model.py", line 3, in <module>
    from sqlmodel import Field, SQLModel, create_engine,\

  File "/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/sqlmodel/__init__.py", line 4, in <module>
    from sqlalchemy.engine import create_mock_engine as create_mock_engine

ImportError: cannot import name 'create_mock_engine' from 'sqlalchemy.engine' (/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py)

```

**Comment by BigOrangeQWQ** [comment]
可以先回退至0.1.0版本
pip install nonebot-plugin-orangedice==0.1.0
看起来似乎是SQLModel的问题

**Comment by A1oneR** [comment]
```
01-17 17:03:50 [ERROR] nonebot | Failed to import "nonebot_plugin_orangedice"
Traceback (most recent call last):

  File "bot.py", line 18, in <module>
    nonebot.load_plugin("nonebot_plugin_orangedice")
    │       └ <function load_plugin at 0x7f6da46c5670>
    └ <module 'nonebot' from '/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/n...

  File "/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
           │       │           └ 'nonebot_plugin_orangedice'
           │       └ <function PluginManager.load_plugin at 0x7f6da46c2a60>
           └ PluginManager(plugins={'nonebot_plugin_orangedice'}, search_path=set())
> File "/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
             │         │             └ 'nonebot_plugin_orangedice'
             │         └ <function import_module at 0x7f6da5bf1700>
             └ <module 'importlib' from '/usr/lib/python3.8/importlib/__init__.py'>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'nonebot_plugin_orangedice'
           │          └ <function _gcd_import at 0x7f6da5d0e430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
                        └ <module 'nonebot_plugin_orangedice' from '/home/lighthouse/zhenxunbot/nonebot_plugin_orangedice/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/home/lighthouse/zhenxunbot/nonebot_plugin_orangedice/__init__.py", line 8, in <module>
    from .card import Card

  File "/home/lighthouse/zhenxunbot/nonebot_plugin_orangedice/card.py", line 12, in <module>
    class Card:

  File "/home/lighthouse/zhenxunbot/nonebot_plugin_orangedice/card.py", line 20, in Card
    def get_card(self, user_id: int) -> dict[str, int]:

TypeError: 'type' object is not subscriptable

```

**Comment by BigOrangeQWQ** [comment]
很抱歉收到再次报错的信息，如果你现在急需使用此插件
请在含有dict[str,int]
文件开头添加如下一行
`from typing import Dict`
然后将dict[str,int]替换成Dict[str,int]
请在含有list[str]
`from typing import List`
将list[str]替换成List[str]
如果您不急需使用此插件，可以等**晚上**修复并发版，
很抱歉没有考虑到版本兼容性的问题。

**Comment by A1oneR** [comment]
没事，还有一个报错
```
01-17 17:18:25 [ERROR] nonebot | Failed to import "nonebot_plugin_orangedice"
Traceback (most recent call last):

  File "bot.py", line 18, in <module>
    nonebot.load_plugin("nonebot_plugin_orangedice")
    │       └ <function load_plugin at 0x7f2e5812b670>
    └ <module 'nonebot' from '/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/n...

  File "/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
           │       │           └ 'nonebot_plugin_orangedice'
           │       └ <function PluginManager.load_plugin at 0x7f2e58127a60>
           └ PluginManager(plugins={'nonebot_plugin_orangedice'}, search_path=set())
> File "/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
             │         │             └ 'nonebot_plugin_orangedice'
             │         └ <function import_module at 0x7f2e59655700>
             └ <module 'importlib' from '/usr/lib/python3.8/importlib/__init__.py'>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'nonebot_plugin_orangedice'
           │          └ <function _gcd_import at 0x7f2e59772430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/lighthouse/.cache/pypoetry/virtualenvs/zhenxun-bot-s0gCDJQV-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
                        └ <module 'nonebot_plugin_orangedice' from '/home/lighthouse/zhenxunbot/nonebot_plugin_orangedice/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/home/lighthouse/zhenxunbot/nonebot_plugin_orangedice/__init__.py", line 11, in <module>
    from .roll import RA, RD

  File "/home/lighthouse/zhenxunbot/nonebot_plugin_orangedice/roll.py", line 6, in <module>
    from .dice import Lexer, Parser

  File "/home/lighthouse/zhenxunbot/nonebot_plugin_orangedice/dice.py", line 118, in <module>
    class Parser:

  File "/home/lighthouse/zhenxunbot/nonebot_plugin_orangedice/dice.py", line 216, in Parser
    def atom(self) -> float|int:

TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by BigOrangeQWQ** [comment]
from typing import Union
将float|int改为Union[float,int]

**Comment by A1oneR** [comment]
安装问题应该暂时告一段落了，感谢抽空解答
