### ISSUE TITLE
插件导入失败, python3.9无法使用?

### ISSUE THREAD

**Issue by Yuelioi** [BigOrangeQWQ/nonebot_plugin_orangedice#17]
03-27 16:03:20 [ERROR] nonebot | Failed to import "nonebot_plugin_orangedice"

Traceback (most recent call last):
  File "/www/wwwroot/project/Robot/nobot1/bot.py", line 12, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/www/wwwroot/project/Robot/nobot1/.venv/lib/python3.9/site-packages/nonebot/plugin/load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)

....

  File "/www/wwwroot/project/Robot/nobot1/.venv/lib/python3.9/site-packages/nonebot_plugin_orangedice/__init__.py", line 1, in <module>
    from ast import MatchSequence
ImportError: cannot import name 'MatchSequence' from 'ast' (/www/server/python_manager/versions/3.9.10/lib/python3.9/ast.py)

搜了下 MatchSequence 是3.10的语法, 我的版本是3.9.10

**Comment by BigOrangeQWQ** [comment]
这是import被ide乱推荐之后忘删的原因，
晚上会释放一个新版本修复之前的和这个bug
